In [58]:
import numpy as np

In [73]:
houses=np.genfromtxt("Houses.csv", delimiter =",", dtype=int)

In [74]:
houses

array([[212000,   4148,  25264],
       [230000,   2501,  11891],
       [339000,   4374,  25351],
       [289000,   2398,  22215],
       [160000,   2536,   9234],
       [ 85000,   2368,  13329],
       [ 85000,   1264,   8407],
       [145000,   1572,  12588],
       [164000,   2375,  16204],
       [123500,   1161,   9626],
       [180000,   1542,   8755],
       [159500,   1464,  14636],
       [156000,   2240,  21780],
       [146500,   1269,  11250],
       [101500,    924,   7361],
       [109800,    768,  10497],
       [182000,   1320,  15768],
       [110000,   1845,  12153],
       [125000,   1274,  13634],
       [ 80000,   1905,  10890]])

In [75]:
# question 1 convertir le prix des maisons en euros
houses[:,0]=houses[:,0]*0.86


In [76]:
#question 2 convertir la surface maison et surface terrain 
houses[:,1:]=houses[:,1:]*0.09
print(houses)


[[182320    373   2273]
 [197800    225   1070]
 [291540    393   2281]
 [248540    215   1999]
 [137600    228    831]
 [ 73100    213   1199]
 [ 73100    113    756]
 [124700    141   1132]
 [141040    213   1458]
 [106210    104    866]
 [154800    138    787]
 [137170    131   1317]
 [134160    201   1960]
 [125990    114   1012]
 [ 87290     83    662]
 [ 94428     69    944]
 [156520    118   1419]
 [ 94600    166   1093]
 [107500    114   1227]
 [ 68800    171    980]]


In [77]:
#question 3 combien de maison surface terrain plus de 1000m2
len(houses[houses[:,2]>1000])


13

In [78]:
#somme des maisons vendu
sum(houses[:,0])

2737208

In [79]:
#taille de la maison la plus chere
prix_max=max(houses[:,0])
print(prix_max)
houses[houses[:,0]==prix_max]

291540


array([[291540,    393,   2281]])

In [88]:
# spliter concatener
array1,array2,array3=np.vsplit(houses,[20,20])
print(array1,array2,array3)

[[182320    373   2273]
 [197800    225   1070]
 [291540    393   2281]
 [248540    215   1999]
 [137600    228    831]
 [ 73100    213   1199]
 [ 73100    113    756]
 [124700    141   1132]
 [141040    213   1458]
 [106210    104    866]
 [154800    138    787]
 [137170    131   1317]
 [134160    201   1960]
 [125990    114   1012]
 [ 87290     83    662]
 [ 94428     69    944]
 [156520    118   1419]
 [ 94600    166   1093]
 [107500    114   1227]
 [ 68800    171    980]] [] []


In [89]:
np.vstack([array1,array2,array3])

array([[182320,    373,   2273],
       [197800,    225,   1070],
       [291540,    393,   2281],
       [248540,    215,   1999],
       [137600,    228,    831],
       [ 73100,    213,   1199],
       [ 73100,    113,    756],
       [124700,    141,   1132],
       [141040,    213,   1458],
       [106210,    104,    866],
       [154800,    138,    787],
       [137170,    131,   1317],
       [134160,    201,   1960],
       [125990,    114,   1012],
       [ 87290,     83,    662],
       [ 94428,     69,    944],
       [156520,    118,   1419],
       [ 94600,    166,   1093],
       [107500,    114,   1227],
       [ 68800,    171,    980]])